[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "asgi-cli"
dynamic = ["version"]
description = "Call ASGI Python application from command line, just like CURL"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Andriy Kornatskyy", email = "andriy.kornatskyy@live.com"}
]
keywords = []
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Environment :: Web Environment",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = []

[project.urls]
Homepage = "https://github.com/akornatskyy/asgi-cli"

[project.scripts]
asgi-cli = "asgi_cli.main:main"

[tool.setuptools]
zip-safe = true

[tool.setuptools.dynamic]
version = {attr = "asgi_cli.__version__"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
asgi_cli = ["py.typed"]

[tool.coverage.run]
source = ["src/asgi_cli"]
omit = ["*/test_*.py", "*/tests/*"]
